/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandardRouteImport } from './routes/standard'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ButtercreamsRouteImport } from './routes/buttercreams'
import { Route as IndexRouteImport } from './routes/index'

const StandardRoute = StandardRouteImport.update({
  id: '/standard',
  path: '/standard',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtercreamsRoute = ButtercreamsRouteImport.update({
  id: '/buttercreams',
  path: '/buttercreams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buttercreams': typeof ButtercreamsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/rewards': typeof RewardsRoute
  '/standard': typeof StandardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buttercreams': typeof ButtercreamsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/rewards': typeof RewardsRoute
  '/standard': typeof StandardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buttercreams': typeof ButtercreamsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/our-story': typeof OurStoryRoute
  '/rewards': typeof RewardsRoute
  '/standard': typeof StandardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buttercreams'
    | '/careers'
    | '/contact'
    | '/menu'
    | '/our-story'
    | '/rewards'
    | '/standard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buttercreams'
    | '/careers'
    | '/contact'
    | '/menu'
    | '/our-story'
    | '/rewards'
    | '/standard'
  id:
    | '__root__'
    | '/'
    | '/buttercreams'
    | '/careers'
    | '/contact'
    | '/menu'
    | '/our-story'
    | '/rewards'
    | '/standard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtercreamsRoute: typeof ButtercreamsRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  MenuRoute: typeof MenuRoute
  OurStoryRoute: typeof OurStoryRoute
  RewardsRoute: typeof RewardsRoute
  StandardRoute: typeof StandardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standard': {
      id: '/standard'
      path: '/standard'
      fullPath: '/standard'
      preLoaderRoute: typeof StandardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buttercreams': {
      id: '/buttercreams'
      path: '/buttercreams'
      fullPath: '/buttercreams'
      preLoaderRoute: typeof ButtercreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtercreamsRoute: ButtercreamsRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  MenuRoute: MenuRoute,
  OurStoryRoute: OurStoryRoute,
  RewardsRoute: RewardsRoute,
  StandardRoute: StandardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
